# SPDX-FileCopyrightText: The go-mail Authors
#
# SPDX-License-Identifier: MIT

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
