# SPDX-FileCopyrightText: The go-mail Authors
#
# SPDX-License-Identifier: MIT

name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  lint:
    name: golangci-lint (${{ matrix.go }})
    runs-on: ubuntu-latest
    concurrency:
      group: ci-lint-${{ matrix.go }}
      cancel-in-progress: true
    strategy:
      matrix:
        go: [ '1.25' ]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit
      - name: Setup go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - name: Checkout Code
        uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
      - name: golangci-lint
        uses: golangci/golangci-lint-action@1481404843c368bc19ca9406f87d6e0fc97bdcfd # v7.0.0
        with:
          version: latest
